import { Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Job } from 'bullmq';
import sharp from 'sharp';
import { DatabaseService } from '../database/database.service';
import { SettingsService } from '../settings/settings.service';
import { StorageService } from '../storage/storage.service';
import {
  checkBookCostLimit,
  CostLimitExceededError,
  buildIllustrationPrompt,
  buildPersonalizationEditPrompt,
  buildNegativePrompt,
  personalizeText,
  generatePersonalizedImage,
  type ReferenceImage,
  type ImageProvider,
} from '@kutty-story/ai';

/** Per-image cost estimate (cents) used for budget enforcement + logging.
 *  OpenAI runs gpt-image-1.5 at quality:'high' + input_fidelity:'high' for
 *  faithful likeness (~20c/image). 28 pages × 20c = 560c, under the raised
 *  MAX_GENERATION_COST_PER_BOOK_CENTS (800) with regen headroom. */
export const COST_PER_IMAGE_CENTS: Record<ImageProvider, number> = {
  gemini: 4,
  openai: 20,
  // fal PuLID-Flux ≈ $0.033/image (1MP) → 28 pages ≈ 92c, well under the cap.
  fal: 4,
};

/** Free preview is limited to the first few pages; the full book is gated
 *  behind sign-up and generated by the full-book processor. */
export const PREVIEW_PAGE_COUNT = 5;

/** Default pages generated in parallel. Higher = faster wall-clock with no
 *  quality change; bounded only by the provider's rate limits (transient 429s
 *  are absorbed by the per-page retry/backoff). Override per-deployment with
 *  the GENERATION_CONCURRENCY env var. 6 lets a 5-page preview run in one wave. */
export const PAGE_CONCURRENCY = 6;

/** Per-page retry policy. A transient API/storage failure retries THAT page
 *  only (with exponential backoff), so one hiccup never drops the page. */
const MAX_PAGE_ATTEMPTS = 3;
const RETRY_BASE_DELAY_MS = 2000;

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Run `fn` with up to `attempts` tries, exponential backoff + jitter between. */
async function withRetry<T>(
  fn: () => Promise<T>,
  label: string,
  logger: Logger,
  attempts = MAX_PAGE_ATTEMPTS,
  baseMs = RETRY_BASE_DELAY_MS,
): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      if (attempt < attempts) {
        const backoff = baseMs * 2 ** (attempt - 1);
        const jitter = Math.floor(Math.random() * 0.3 * backoff);
        const delay = backoff + jitter;
        logger.warn(
          `${label} attempt ${attempt}/${attempts} failed: ${err}. Retrying in ${delay}ms`,
        );
        await sleep(delay);
      }
    }
  }
  throw lastErr;
}

/** Map over items with a bounded number of concurrent workers (a pool). */
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let next = 0;
  const worker = async (): Promise<void> => {
    for (;;) {
      const i = next++;
      if (i >= items.length) return;
      results[i] = await fn(items[i], i);
    }
  };
  const poolSize = Math.min(limit, items.length);
  await Promise.all(Array.from({ length: poolSize }, () => worker()));
  return results;
}

/** Derive the storage key from a stored reference (key or URL). */
function keyFromRef(ref: string): string {
  if (!ref) return ref;
  const filesIdx = ref.indexOf('/files/');
  if (filesIdx >= 0) return ref.slice(filesIdx + '/files/'.length);
  if (/^https?:\/\//i.test(ref)) {
    try {
      return new URL(ref).pathname.replace(/^\/+/, '');
    } catch {
      return ref;
    }
  }
  return ref.replace(/^\/+/, '');
}

function mimeFromKey(key: string): string {
  const ext = key.split('.').pop()?.toLowerCase();
  if (ext === 'png') return 'image/png';
  if (ext === 'webp') return 'image/webp';
  if (ext === 'heic') return 'image/heic';
  if (ext === 'heif') return 'image/heif';
  return 'image/jpeg';
}

/** Load the child's reference photos from storage (best-effort). */
async function loadReferenceImages(
  storage: StorageService,
  refs: string[],
  logger: Logger,
): Promise<ReferenceImage[]> {
  const out: ReferenceImage[] = [];
  for (const ref of (refs || []).slice(0, 3)) {
    const key = keyFromRef(ref);
    try {
      const data = await storage.read(key);
      out.push({ data, mimeType: mimeFromKey(key) });
    } catch (err) {
      logger.warn(`Could not read reference image ${key}: ${err}`);
    }
  }
  return out;
}

/** Fetch the existing (sample) story page illustration to personalize. */
async function fetchBaseIllustration(
  webUrl: string,
  slug: string,
  pageNumber: number,
  logger: Logger,
): Promise<ReferenceImage | undefined> {
  const url = `${webUrl}/images/stories/${slug}/page-${pageNumber}.jpg`;
  try {
    const res = await fetch(url);
    if (!res.ok) return undefined;
    const data = Buffer.from(await res.arrayBuffer());
    return { data, mimeType: 'image/jpeg' };
  } catch (err) {
    logger.warn(`Could not fetch base illustration ${url}: ${err}`);
    return undefined;
  }
}

interface BookForGeneration {
  id: string;
  language: string;
  story: { artStyle: string; slug: string };
  child: {
    name: string;
    nickname: string | null;
    ageYears: number;
    gender: string;
    skinTone: string | null;
    hairColor: string | null;
    hasGlasses: boolean;
  };
}

interface PageTemplateLike {
  pageNumber: number;
  textEnglish: string;
  textTamil: string | null;
  illustrationPrompt: string;
  negativePrompt: string | null;
  styleTokens: unknown;
}

/** Trim a generated image to a clean 1024x1024 square (no stray padding/bars). */
async function toSquarePng(buffer: Buffer): Promise<Buffer> {
  return sharp(buffer)
    .resize(1024, 1024, { fit: 'cover', position: 'center' })
    .png()
    .toBuffer();
}

function escapeXml(s: string): string {
  return s.replace(
    /[<>&'"]/g,
    (c) =>
      ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' })[
        c
      ] as string,
  );
}

/** Greedy word-wrap into at most `maxChars`-wide lines. */
function wrapCaption(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = '';
  for (const w of words) {
    if (cur && (cur + ' ' + w).length > maxChars) {
      lines.push(cur);
      cur = w;
    } else {
      cur = cur ? `${cur} ${w}` : w;
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

/**
 * Bake a caption onto the bottom of a square page image (semi-transparent band
 * + centered white text), via an SVG composite. Used for providers that
 * generate a fresh scene without rendering the page's title text (fal/PuLID) —
 * so those pages match the template-edit providers that bake the text in.
 */
async function overlayCaption(buffer: Buffer, caption: string): Promise<Buffer> {
  const text = (caption || '').trim();
  if (!text) return buffer;

  const size = 1024;
  const fontSize = 40;
  const lineHeight = 52;
  const padding = 28;
  const lines = wrapCaption(text, 32).slice(0, 4);
  const bandH = lines.length * lineHeight + padding * 2;
  const bandY = size - bandH;
  const firstBaseline = bandY + padding + fontSize - 8;

  const tspans = lines
    .map(
      (ln, i) =>
        `<tspan x="${size / 2}" dy="${i === 0 ? 0 : lineHeight}">${escapeXml(ln)}</tspan>`,
    )
    .join('');

  const svg = `<svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="${bandY}" width="${size}" height="${bandH}" fill="#000000" fill-opacity="0.55"/>
    <text y="${firstBaseline}" font-family="Arial, Helvetica, sans-serif" font-size="${fontSize}" font-weight="700" fill="#FFFFFF" text-anchor="middle">${tspans}</text>
  </svg>`;

  return sharp(buffer)
    .composite([{ input: Buffer.from(svg), top: 0, left: 0 }])
    .png()
    .toBuffer();
}

/**
 * Generate one personalized page and store it.
 *
 * Edit-in-place (default, with `baseImage`): the template illustration is the
 * FIRST reference and the child's photo(s) follow — the model swaps the cartoon
 * face to the real child and edits the name, preserving the template scene/style.
 * Best on OpenAI gpt-image-1. Without a template it generates the scene fresh
 * from the prompt + child photos.
 */
async function generateAndStorePage(
  storage: StorageService,
  provider: ImageProvider,
  apiKey: string,
  book: BookForGeneration,
  page: PageTemplateLike,
  childRefs: ReferenceImage[],
  baseImage?: ReferenceImage,
): Promise<{
  imageUrl: string;
  prompt: string;
  negativePrompt: string;
  textContent: string;
  costCents: number;
  latencyMs: number;
}> {
  const negativePrompt = buildNegativePrompt(page.negativePrompt || undefined);

  const textContent =
    book.language === 'TAMIL' && page.textTamil
      ? personalizeText(page.textTamil, {
          childName: book.child.name,
          nickname: book.child.nickname || book.child.name,
        })
      : personalizeText(page.textEnglish, {
          childName: book.child.name,
          nickname: book.child.nickname || book.child.name,
        });

  // The name baked into the template is English; target the English caption.
  const captionEnglish = personalizeText(page.textEnglish, {
    childName: book.child.name,
    nickname: book.child.nickname || book.child.name,
  });

  let prompt: string;
  let referenceImages: ReferenceImage[];

  if (baseImage) {
    prompt = buildPersonalizationEditPrompt({
      childName: book.child.name,
      caption: captionEnglish,
    });
    // Template first (the image to edit), then the child's photo(s).
    referenceImages = [baseImage, ...childRefs];
  } else {
    prompt = buildIllustrationPrompt({
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      styleTokens: (page.styleTokens as any) || {
        style: book.story.artStyle,
        medium: 'digital illustration',
        palette: 'warm and vibrant',
        lighting: 'soft natural lighting',
      },
      character: {
        childName: book.child.name,
        ageYears: book.child.ageYears,
        gender: book.child.gender,
        skinTone: book.child.skinTone || undefined,
        hairColor: book.child.hairColor || undefined,
        hasGlasses: book.child.hasGlasses,
      },
      sceneDescription: page.illustrationPrompt,
    });
    referenceImages = childRefs;
  }

  const result = await generatePersonalizedImage({
    provider,
    apiKey,
    prompt,
    negativePrompt,
    referenceImages,
  });

  let squareBuffer = await toSquarePng(result.buffer);

  // fal/PuLID renders a fresh scene without the page's title text, so bake the
  // caption on. Template-edit providers (openai/gemini) already have it baked
  // into the edited illustration — leave those untouched.
  if (provider === 'fal') {
    squareBuffer = await overlayCaption(squareBuffer, textContent);
  }

  const key = `generated/${book.id}/page-${page.pageNumber}.png`;
  const { url } = await storage.save(key, squareBuffer, 'image/png');

  return {
    imageUrl: url,
    prompt,
    negativePrompt,
    textContent,
    costCents: COST_PER_IMAGE_CENTS[provider],
    latencyMs: result.latencyMs,
  };
}

function toBookForGeneration(book: {
  id: string;
  language: string;
  story: { artStyle: string; slug: string };
  child: {
    name: string;
    nickname: string | null;
    ageYears: number;
    gender: string;
    skinTone: string | null;
    hairColor: string | null;
    hasGlasses: boolean;
  };
}): BookForGeneration {
  return {
    id: book.id,
    language: book.language,
    story: { artStyle: book.story.artStyle, slug: book.story.slug },
    child: {
      name: book.child.name,
      nickname: book.child.nickname,
      ageYears: book.child.ageYears,
      gender: book.child.gender,
      skinTone: book.child.skinTone,
      hairColor: book.child.hairColor,
      hasGlasses: book.child.hasGlasses,
    },
  };
}

export interface GenerateBookPagesOptions {
  db: DatabaseService;
  settings: SettingsService;
  storage: StorageService;
  config: ConfigService;
  logger: Logger;
  job: Job<{ bookId: string }>;
  bookId: string;
  /** Used as the aiUsageLog `operation` value. */
  operation: string;
  /** Restrict to the first N pages (preview). Omit for the full 28-page book. */
  previewLimit?: number;
  /** Book status while the job runs. */
  runningStatus: 'GENERATING_PREVIEW' | 'GENERATING_FULL';
  /** Book status set once every target page is verified READY. */
  successStatus: 'PREVIEW_READY' | 'PENDING_APPROVAL';
  /** Book status restored if the job fails (so the user can retry cleanly). */
  failureStatus: 'DRAFT' | 'PREVIEW_READY';
  /** Timestamp column stamped on success. */
  successTimestampField: 'previewGeneratedAt' | 'fullGeneratedAt';
  /** Invoked after the book reaches `successStatus` (e.g. deliver the PDF). */
  onComplete?: () => Promise<void>;
}

/**
 * Shared, fault-tolerant page-generation engine used by BOTH the preview and
 * full-book processors so the 28-page generation behaves identically for every
 * downstream delivery format (PDF download and printed book).
 *
 * Guarantees:
 *  - every target page is tracked in `BookPage` (PENDING → GENERATING → READY|FAILED);
 *  - pages generate in bounded chunks (PAGE_CONCURRENCY) to respect rate limits;
 *  - each page retries independently with exponential backoff;
 *  - the book only reaches `successStatus` once a barrier confirms ALL target
 *    pages are READY — otherwise the job throws and the status is rolled back.
 */
export async function generateBookPages(
  opts: GenerateBookPagesOptions,
): Promise<void> {
  const {
    db,
    settings,
    storage,
    config,
    logger,
    job,
    bookId,
    operation,
    previewLimit,
    runningStatus,
    successStatus,
    failureStatus,
    successTimestampField,
    onComplete,
  } = opts;

  try {
    const { provider, apiKey, enabled } =
      await settings.getActiveImageProviderConfig();

    if (!enabled || !apiKey) {
      throw new Error(
        'Image generation is not configured. Set the provider API key and enable it in admin settings.',
      );
    }

    await db.book.update({
      where: { id: bookId },
      data: { status: runningStatus },
    });

    const book = await db.book.findUnique({
      where: { id: bookId },
      include: {
        child: true,
        story: { include: { pages: { orderBy: { pageNumber: 'asc' } } } },
        pages: true,
      },
    });

    if (!book) {
      throw new Error(`Book ${bookId} not found`);
    }

    // The set of pages this pipeline is responsible for. Preview = the first
    // few (preview-flagged) pages; full = every page in the story (all 28).
    const markedPreview = book.story.pages.filter((p) => p.isPreviewPage);
    const targetPages =
      previewLimit != null
        ? (markedPreview.length ? markedPreview : book.story.pages).slice(
            0,
            previewLimit,
          )
        : book.story.pages;
    const targetPageNumbers = targetPages.map((p) => p.pageNumber);

    // Skip pages already done (idempotent on job retry); (re)generate the rest.
    // A non-READY status (PENDING/GENERATING/FAILED/REGEN_REQUESTED) or a
    // missing image both mean the page still needs work.
    const byNumber = new Map(book.pages.map((bp) => [bp.pageNumber, bp]));
    const workPages = targetPages.filter((t) => {
      const existing = byNumber.get(t.pageNumber);
      return !existing || existing.status !== 'READY' || !existing.finalImageUrl;
    });

    const childRefs = await loadReferenceImages(
      storage,
      book.child.referencePhotoUrls,
      logger,
    );
    // Without a readable reference photo the model has nothing to swap the
    // face from and would just return the template unchanged — fail loudly
    // (and avoid billing for un-personalized pages) instead.
    if (childRefs.length === 0) {
      throw new Error(
        'No usable reference photo for the child. The uploaded photo could not be read — please re-upload a clear, front-facing photo.',
      );
    }

    const bookForGen = toBookForGeneration(book);
    const webUrl = config.get<string>('WEB_URL') || 'http://localhost:3000';

    // Pre-seed per-page state so pages 1..N are individually tracked even
    // before (or if) generation succeeds.
    for (const page of workPages) {
      await db.bookPage.upsert({
        where: { bookId_pageNumber: { bookId, pageNumber: page.pageNumber } },
        create: { bookId, pageNumber: page.pageNumber, status: 'GENERATING' },
        update: { status: 'GENERATING' },
      });
    }

    // Running cost across concurrent workers. JS is single-threaded, so these
    // mutations are atomic between `await`s; `reserved` accounts for in-flight
    // pages so the budget check can't be raced past the limit.
    let costCents = book.totalImageGenCostCents;
    let reserved = 0;
    let completed = 0;
    const perImageCost = COST_PER_IMAGE_CENTS[provider];
    const concurrency = Math.max(
      1,
      Number(config.get<string>('GENERATION_CONCURRENCY')) || PAGE_CONCURRENCY,
    );

    const results = await mapWithConcurrency(
      workPages,
      concurrency,
      async (page) => {
        // Budget gate (NOT retried — exceeding the cap is terminal).
        checkBookCostLimit(bookId, costCents + reserved, perImageCost);
        reserved += perImageCost;

        try {
          const gen = await withRetry(
            async () => {
              // fal/PuLID generates a fresh illustration from the prompt + the
              // child's face (identity-preserving) — it does not edit the
              // template, so skip the base illustration for it. OpenAI/Gemini
              // keep using the template-edit path unchanged.
              const baseImage =
                provider === 'fal'
                  ? undefined
                  : await fetchBaseIllustration(
                      webUrl,
                      book.story.slug,
                      page.pageNumber,
                      logger,
                    );
              return generateAndStorePage(
                storage,
                provider,
                apiKey,
                bookForGen,
                page,
                childRefs,
                baseImage,
              );
            },
            `page ${page.pageNumber}`,
            logger,
          );

          reserved -= perImageCost;
          costCents += gen.costCents;

          await db.bookPage.update({
            where: {
              bookId_pageNumber: { bookId, pageNumber: page.pageNumber },
            },
            data: {
              status: 'READY',
              finalImageUrl: gen.imageUrl,
              generationCostCents: gen.costCents,
              generatedAt: new Date(),
              generationAttempts: {
                push: {
                  attempt: 1,
                  prompt: gen.prompt,
                  negativePrompt: gen.negativePrompt,
                  textContent: gen.textContent,
                  imageUrl: gen.imageUrl,
                  costCents: gen.costCents,
                  timestamp: new Date().toISOString(),
                },
              },
            },
          });

          await db.aiUsageLog.create({
            data: {
              provider,
              operation,
              bookId,
              pageNumber: page.pageNumber,
              costCents: gen.costCents,
              latencyMs: gen.latencyMs,
              success: true,
            },
          });

          logger.log(`Generated page ${page.pageNumber} for book ${bookId}`);
          return { pageNumber: page.pageNumber, ok: true as const };
        } catch (err) {
          reserved -= perImageCost;
          const message = err instanceof Error ? err.message : String(err);

          await db.bookPage.update({
            where: {
              bookId_pageNumber: { bookId, pageNumber: page.pageNumber },
            },
            data: {
              status: 'FAILED',
              generationAttempts: {
                push: {
                  attempt: MAX_PAGE_ATTEMPTS,
                  error: message,
                  timestamp: new Date().toISOString(),
                },
              },
            },
          });

          await db.aiUsageLog.create({
            data: {
              provider,
              operation,
              bookId,
              pageNumber: page.pageNumber,
              costCents: 0,
              latencyMs: 0,
              success: false,
              errorMessage: message.slice(0, 500),
            },
          });

          logger.error(
            `Page ${page.pageNumber} for book ${bookId} failed after ${MAX_PAGE_ATTEMPTS} attempts: ${message}`,
          );
          return { pageNumber: page.pageNumber, ok: false as const };
        } finally {
          completed += 1;
          await job.updateProgress(
            Math.round((completed / Math.max(workPages.length, 1)) * 100),
          );
        }
      },
    );

    // === STRICT COMPLETION BARRIER ===
    // Re-read state from the DB (source of truth) and require EVERY target page
    // to be READY before the book is allowed to advance. No partial books.
    const finalPages = await db.bookPage.findMany({
      where: { bookId, pageNumber: { in: targetPageNumbers } },
    });
    const readyNumbers = new Set(
      finalPages
        .filter((p) => p.status === 'READY' && p.finalImageUrl)
        .map((p) => p.pageNumber),
    );
    const missing = targetPageNumbers.filter((n) => !readyNumbers.has(n));

    if (missing.length > 0) {
      const failedThisRun = results.filter((r) => r && !r.ok).length;
      throw new Error(
        `Generation incomplete for book ${bookId}: ${readyNumbers.size}/${targetPageNumbers.length} pages ready. ` +
          `Missing/failed pages: [${missing.join(', ')}] (${failedThisRun} failed this run). ` +
          `Will retry on next job attempt.`,
      );
    }

    await db.book.update({
      where: { id: bookId },
      data: {
        status: successStatus,
        totalImageGenCostCents: costCents,
        ...(successTimestampField === 'previewGeneratedAt'
          ? { previewGeneratedAt: new Date() }
          : { fullGeneratedAt: new Date() }),
      },
    });

    logger.log(
      `Generation complete for book ${bookId}: ${readyNumbers.size}/${targetPageNumbers.length} pages. ` +
        `Total cost: ${costCents} cents`,
    );

    if (onComplete) {
      try {
        await onComplete();
      } catch (err) {
        // Post-completion side effects (e.g. PDF email) must never fail the job
        // or roll back the verified pages.
        logger.error(`onComplete hook failed for book ${bookId}: ${err}`);
      }
    }
  } catch (error) {
    const isBudget = error instanceof CostLimitExceededError;
    logger.error(
      `Generation failed for book ${bookId} (${operation}): ${error}`,
    );
    await db.book.update({
      where: { id: bookId },
      data: { status: failureStatus },
    });
    // Budget overruns are terminal — rethrowing still surfaces them, but the
    // message makes the cause explicit in the failed-job record.
    if (isBudget) {
      throw new Error(`Book ${bookId} hit the generation cost limit: ${error}`);
    }
    throw error;
  }
}
